import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useAuth, useUser } from '@clerk/clerk-expo';
import { createClerkSupabaseClient } from '../database/supabaseClient';

export interface Task {
    title: string;
    xp: number;
    completed: boolean;
}

export interface Quest {
    id: string;
    title: string;
    icon: string;
    iconColor: string;
    deadline: string;
    deadlineBg: string;
    deadlineColor: string;
    deadlineIcon: string;
    progressColor: string;
    tasks: Task[];
}

interface QuestContextType {
    quests: Quest[];
    addQuest: (quest: Quest) => void;
    toggleTask: (questId: string, taskIndex: number) => void;
    getProgress: (quest: Quest) => number;
    totalXP: number;
    isLoading: boolean;
    replaceAllQuests: (newQuests: Quest[]) => Promise<void>;
    removeQuest: (questId: string) => Promise<void>;
    reloadQuests: () => Promise<void>;
}

const QuestContext = createContext<QuestContextType | undefined>(undefined);



export function QuestProvider({ children }: { children: ReactNode }) {
    const [quests, setQuests] = useState<Quest[]>([]);
    const [isLoading, setIsLoading] = useState(true);

    const { getToken } = useAuth();
    const { user } = useUser();

    // Helper: get authenticated Supabase client
    const getSupabase = async () => {
        const token = await getToken({ template: 'Supabase' });
        if (!token) return null;
        return createClerkSupabaseClient(token);
    };

    // Reusable quest loader
    const loadQuests = async () => {
        if (!user) return;
        setIsLoading(true);
        try {
            const supabase = await getSupabase();
            if (!supabase) {
                setQuests([]);
                setIsLoading(false);
                return;
            }

            const { data, error } = await supabase
                .from('quests')
                .select('*')
                .eq('clerk_user_id', user.id);

            if (error) {
                console.error('❌ QuestContext: Query error:', JSON.stringify(error));
                setQuests([]);
            } else if (data && data.length > 0) {
                setQuests(data);
            } else {
                console.log('🆕 QuestContext: No quests yet — will be generated by AI');
                setQuests([]);
            }
        } catch (err) {
            console.error("❌ QuestContext: Unexpected error:", err);
            setQuests([]);
        } finally {
            setIsLoading(false);
        }
    };

    // 1. Fetch data from Supabase on Load
    useEffect(() => {
        loadQuests();
    }, [user]);

    // 2. Add Quest & Sync to Cloud
    const addQuest = async (quest: Quest) => {
        setQuests(prev => [...prev, quest]);
        if (!user) return;
        const supabase = await getSupabase();
        if (!supabase) return;
        await supabase.from('quests').insert([{ ...quest, clerk_user_id: user.id }]);
    };

    // 3. Toggle Task & Sync to Cloud
    const toggleTask = async (questId: string, taskIndex: number) => {
        const currentQuest = quests.find(q => q.id === questId);
        if (!currentQuest) return;

        const currentTask = currentQuest.tasks[taskIndex];
        const isNowCompleted = !currentTask.completed;

        const updatedTasks = [...currentQuest.tasks];
        updatedTasks[taskIndex] = {
            ...currentTask,
            completed: isNowCompleted,
        };
        const modifiedQuest = { ...currentQuest, tasks: updatedTasks };

        setQuests(prev => prev.map(q => q.id === questId ? modifiedQuest : q));

        if (!user) return;
        try {
            const supabase = await getSupabase();
            if (!supabase) return;

            // Sync task state
            await supabase
                .from('quests')
                .update({ tasks: modifiedQuest.tasks })
                .eq('id', questId)
                .eq('clerk_user_id', user.id);

            // --- XP & LEVEL & QUESTS COMPLETION SYNC ---
            const { data: stats } = await supabase
                .from('player_stats')
                .select('total_xp, level, quests_completed')
                .eq('clerk_user_id', user.id)
                .single();

            if (stats) {
                const xpChange = isNowCompleted ? currentTask.xp : -currentTask.xp;
                const newTotalXP = Math.max(0, (stats.total_xp || 0) + xpChange);
                const newLevel = Math.floor(newTotalXP / 2000) + 1; // 2000 XP per level

                // Only increment on completion, decrement if un-checking
                const questChange = isNowCompleted ? 1 : -1;
                const newQuestsCompleted = Math.max(0, (stats.quests_completed || 0) + questChange);

                await supabase
                    .from('player_stats')
                    .update({
                        total_xp: newTotalXP,
                        level: newLevel,
                        quests_completed: newQuestsCompleted
                    })
                    .eq('clerk_user_id', user.id);
            }
        } catch (err) {
            console.error("Failed to sync task toggle and XP:", err);
        }
    };

    // 4. Replace ALL quests (AI bulk-set after generation)
    const replaceAllQuests = async (newQuests: Quest[]) => {
        setQuests(newQuests);
        if (!user) return;
        try {
            const supabase = await getSupabase();
            if (!supabase) return;
            // Delete existing quests for this user
            await supabase.from('quests').delete().eq('clerk_user_id', user.id);
            // Insert new ones
            if (newQuests.length > 0) {
                const questsWithUser = newQuests.map(q => ({ ...q, clerk_user_id: user.id }));
                await supabase.from('quests').insert(questsWithUser);
            }
            console.log('✅ QuestContext: Replaced all quests with', newQuests.length, 'AI-generated quests');
        } catch (err) {
            console.error("❌ QuestContext: Failed to replace quests:", err);
        }
    };

    // 5. Remove a single quest (AI cleanup)
    const removeQuest = async (questId: string) => {
        setQuests(prev => prev.filter(q => q.id !== questId));
        if (!user) return;
        try {
            const supabase = await getSupabase();
            if (!supabase) return;
            await supabase.from('quests').delete().eq('id', questId).eq('clerk_user_id', user.id);
            console.log('🗑️ QuestContext: Removed quest', questId);
        } catch (err) {
            console.error("❌ QuestContext: Failed to remove quest:", err);
        }
    };

    // 6. Force reload from Supabase (after onboarding / recalibration)
    const reloadQuests = async () => {
        await loadQuests();
    };

    const getProgress = (quest: Quest): number => {
        if (quest.tasks.length === 0) return 0;
        const completed = quest.tasks.filter(t => t.completed).length;
        return Math.round((completed / quest.tasks.length) * 100);
    };

    const totalXP = quests.reduce(
        (sum, q) => sum + q.tasks.filter(t => t.completed).reduce((s, t) => s + t.xp, 0),
        0
    );

    return (
        <QuestContext.Provider value={{ quests, addQuest, toggleTask, getProgress, totalXP, isLoading, replaceAllQuests, removeQuest, reloadQuests }}>
            {children}
        </QuestContext.Provider>
    );
}

export function useQuests() {
    const context = useContext(QuestContext);
    if (!context) throw new Error('useQuests must be used within a QuestProvider');
    return context;
}