import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useAuth, useUser } from '@clerk/clerk-expo';
import { createClerkSupabaseClient } from '../database/supabaseClient';

export interface Task {
    title: string;
    xp: number;
    completed: boolean;
    requiresQuiz?: boolean;
    earnedXp?: number;
    score?: number;
}

export interface Quest {
    id: string;
    title: string;
    icon: string;
    iconColor: string;
    deadline: string;
    deadlineBg: string;
    deadlineColor: string;
    deadlineIcon: string;
    progressColor: string;
    tasks: Task[];
    source?: 'syllabus' | 'ai-chat';
}

interface QuestContextType {
    quests: Quest[];
    addQuest: (quest: Quest) => void;
    toggleTask: (questId: string, taskIndex: number) => void;
    markTaskComplete: (questId: string, taskIndex: number, xpEarned: number) => void;
    getProgress: (quest: Quest) => number;
    totalXP: number;
    isLoading: boolean;
    replaceAllQuests: (newQuests: Quest[]) => Promise<void>;
    removeQuest: (questId: string) => Promise<void>;
    reloadQuests: () => Promise<void>;
    recordFocusSession: (minutes: number, isVictory: boolean) => Promise<number>;
    grantBonusXP: (amount: number) => Promise<void>;
}

const QuestContext = createContext<QuestContextType | undefined>(undefined);



export function QuestProvider({ children }: { children: ReactNode }) {
    const [quests, setQuests] = useState<Quest[]>([]);
    const [isLoading, setIsLoading] = useState(true);

    const { getToken } = useAuth();
    const { user } = useUser();

    // Helper: get authenticated Supabase client
    const getSupabase = async () => {
        const token = await getToken({ template: 'Supabase' });
        if (!token) return null;
        return createClerkSupabaseClient(token);
    };

    // Reusable quest loader
    const loadQuests = async () => {
        if (!user) return;
        setIsLoading(true);
        try {
            const supabase = await getSupabase();
            if (!supabase) {
                setQuests([]);
                setIsLoading(false);
                return;
            }

            const { data, error } = await supabase
                .from('quests')
                .select('*')
                .eq('clerk_user_id', user.id);

            if (error) {
                console.error('❌ QuestContext: Query error:', JSON.stringify(error));
                setQuests([]);
            } else if (data && data.length > 0) {
                // Patch existing quests to ensure 'requiresQuiz' is true for AI/Syllabus tasks
                let needsUpdate = false;
                const patchedData = data.map(q => {
                    const patchedTasks = q.tasks.map((t: Task) => {
                        if (t.requiresQuiz === undefined) {
                            needsUpdate = true;
                            return { ...t, requiresQuiz: true };
                        }
                        return t;
                    });
                    if (q.source === undefined) {
                        needsUpdate = true;
                        q.source = 'syllabus'; // Default old quests to syllabus
                    }
                    return { ...q, tasks: patchedTasks };
                });

                setQuests(patchedData);

                // Silently push the patch up to Supabase if anything changed
                if (needsUpdate) {
                    for (const pq of patchedData) {
                        await supabase.from('quests').update({ tasks: pq.tasks, source: pq.source }).eq('id', pq.id);
                    }
                    console.log('🔧 QuestContext: Patched legacy quests with requiresQuiz flags.');
                }
            } else {
                console.log('🆕 QuestContext: No quests yet — will be generated by AI');
                setQuests([]);
            }
        } catch (err) {
            console.error("❌ QuestContext: Unexpected error:", err);
            setQuests([]);
        } finally {
            setIsLoading(false);
        }
    };

    // 1. Fetch data from Supabase on Load
    useEffect(() => {
        loadQuests();
    }, [user]);

    // 2. Add Quest & Sync to Cloud
    const addQuest = async (quest: Quest) => {
        setQuests(prev => [...prev, quest]);
        if (!user) return;
        const supabase = await getSupabase();
        if (!supabase) return;
        await supabase.from('quests').insert([{ ...quest, clerk_user_id: user.id }]);
    };

    // 3. Toggle Task & Sync to Cloud
    const toggleTask = async (questId: string, taskIndex: number) => {
        const currentQuest = quests.find(q => q.id === questId);
        if (!currentQuest) return;

        const currentTask = currentQuest.tasks[taskIndex];
        const isNowCompleted = !currentTask.completed;

        const updatedTasks = [...currentQuest.tasks];
        updatedTasks[taskIndex] = {
            ...currentTask,
            completed: isNowCompleted,
            earnedXp: isNowCompleted ? currentTask.earnedXp : undefined,
            score: isNowCompleted ? currentTask.score : undefined,
        };
        const modifiedQuest = { ...currentQuest, tasks: updatedTasks };

        setQuests(prev => prev.map(q => q.id === questId ? modifiedQuest : q));

        if (!user) return;
        try {
            const supabase = await getSupabase();
            if (!supabase) return;

            // Sync task state
            await supabase
                .from('quests')
                .update({ tasks: modifiedQuest.tasks })
                .eq('id', questId)
                .eq('clerk_user_id', user.id);

            // --- XP & LEVEL & QUESTS COMPLETION SYNC ---
            const { data: stats } = await supabase
                .from('player_stats')
                .select('total_xp, level, quests_completed')
                .eq('clerk_user_id', user.id)
                .single();

            if (stats) {
                const xpChange = isNowCompleted ? currentTask.xp : -(currentTask.earnedXp ?? currentTask.xp);
                const newTotalXP = Math.max(0, (stats.total_xp || 0) + xpChange);
                const newLevel = Math.floor(newTotalXP / 2000) + 1; // 2000 XP per level

                // Only increment on completion, decrement if un-checking
                const questChange = isNowCompleted ? 1 : -1;
                const newQuestsCompleted = Math.max(0, (stats.quests_completed || 0) + questChange);

                await supabase
                    .from('player_stats')
                    .update({
                        total_xp: newTotalXP,
                        level: newLevel,
                        quests_completed: newQuestsCompleted
                    })
                    .eq('clerk_user_id', user.id);
            }
        } catch (err) {
            console.error("Failed to sync task toggle and XP:", err);
        }
    };

    // 3.5. Mark Task Complete (AI driven, variable XP) & Sync to Cloud
    const markTaskComplete = async (questId: string, taskIndex: number, xpEarned: number) => {
        const currentQuest = quests.find(q => q.id === questId);
        if (!currentQuest) return;

        const currentTask = currentQuest.tasks[taskIndex];
        // Only proceed if not already completed
        if (currentTask.completed) return;

        const score = Math.round((xpEarned / currentTask.xp) * 100);

        const updatedTasks = [...currentQuest.tasks];
        updatedTasks[taskIndex] = {
            ...currentTask,
            completed: true,
            earnedXp: xpEarned,
            score: score,
        };
        const modifiedQuest = { ...currentQuest, tasks: updatedTasks };

        setQuests(prev => prev.map(q => q.id === questId ? modifiedQuest : q));

        if (!user) return;
        try {
            const supabase = await getSupabase();
            if (!supabase) return;

            // Sync task state
            await supabase
                .from('quests')
                .update({ tasks: modifiedQuest.tasks })
                .eq('id', questId)
                .eq('clerk_user_id', user.id);

            // --- XP & LEVEL & QUESTS COMPLETION SYNC ---
            const { data: stats } = await supabase
                .from('player_stats')
                .select('total_xp, level, quests_completed')
                .eq('clerk_user_id', user.id)
                .single();

            if (stats) {
                const newTotalXP = Math.max(0, (stats.total_xp || 0) + xpEarned);
                const newLevel = Math.floor(newTotalXP / 2000) + 1;
                const newQuestsCompleted = Math.max(0, (stats.quests_completed || 0) + 1);

                await supabase
                    .from('player_stats')
                    .update({
                        total_xp: newTotalXP,
                        level: newLevel,
                        quests_completed: newQuestsCompleted
                    })
                    .eq('clerk_user_id', user.id);
            }
        } catch (err) {
            console.error("Failed to sync markTaskComplete and XP:", err);
        }
    };

    // 4. Replace ALL quests (AI bulk-set after generation)
    const replaceAllQuests = async (newQuests: Quest[]) => {
        setQuests(newQuests);
        if (!user) return;
        try {
            const supabase = await getSupabase();
            if (!supabase) return;
            // Delete existing quests for this user
            await supabase.from('quests').delete().eq('clerk_user_id', user.id);
            // Insert new ones
            if (newQuests.length > 0) {
                const questsWithUser = newQuests.map(q => ({ ...q, clerk_user_id: user.id }));
                await supabase.from('quests').insert(questsWithUser);
            }
            console.log('✅ QuestContext: Replaced all quests with', newQuests.length, 'AI-generated quests');
        } catch (err) {
            console.error("❌ QuestContext: Failed to replace quests:", err);
        }
    };

    // 5. Remove a single quest (AI cleanup)
    const removeQuest = async (questId: string) => {
        setQuests(prev => prev.filter(q => q.id !== questId));
        if (!user) return;
        try {
            const supabase = await getSupabase();
            if (!supabase) return;
            await supabase.from('quests').delete().eq('id', questId).eq('clerk_user_id', user.id);
            console.log('🗑️ QuestContext: Removed quest', questId);
        } catch (err) {
            console.error("❌ QuestContext: Failed to remove quest:", err);
        }
    };

    // 6. Force reload from Supabase (after onboarding / recalibration)
    const reloadQuests = async () => {
        await loadQuests();
    };

    // 7. Record Focus Session (Pomodoro RPG)
    const recordFocusSession = async (minutes: number, isVictory: boolean): Promise<number> => {
        if (!user) return 0;
        let xpChange = 0;
        try {
            const supabase = await getSupabase();
            if (!supabase) return 0;

            const { data: stats } = await supabase
                .from('player_stats')
                .select('total_xp, level, focus_sessions_completed, total_focus_minutes')
                .eq('clerk_user_id', user.id)
                .single();

            if (stats) {
                // Formula: 2 XP per minute focused, or a fixed penalty.
                xpChange = isVictory ? Math.round(minutes * 2) : -20;

                // Never go below 0 total XP
                const newTotalXP = Math.max(0, (stats.total_xp || 0) + xpChange);
                const newLevel = Math.floor(newTotalXP / 2000) + 1;

                const newFocusSessions = isVictory ? (stats.focus_sessions_completed || 0) + 1 : (stats.focus_sessions_completed || 0);
                const newTotalMinutes = isVictory ? (stats.total_focus_minutes || Math.round(minutes)) + Math.round(minutes) : (stats.total_focus_minutes || 0);

                await supabase
                    .from('player_stats')
                    .update({
                        total_xp: newTotalXP,
                        level: newLevel,
                        focus_sessions_completed: newFocusSessions,
                        total_focus_minutes: newTotalMinutes
                    })
                    .eq('clerk_user_id', user.id);
            }
        } catch (err) {
            console.error("❌ QuestContext: Failed to record focus session:", err);
        }
        return xpChange;
    };

    // 8. Grant raw Bonus XP (e.g. for PYQ Mock Exams)
    const grantBonusXP = async (amount: number) => {
        if (!user || amount <= 0) return;
        try {
            const supabase = await getSupabase();
            if (!supabase) return;

            const { data: stats } = await supabase
                .from('player_stats')
                .select('total_xp, level')
                .eq('clerk_user_id', user.id)
                .single();

            if (stats) {
                const newTotalXP = (stats.total_xp || 0) + amount;
                const newLevel = Math.floor(newTotalXP / 2000) + 1;

                await supabase
                    .from('player_stats')
                    .update({
                        total_xp: newTotalXP,
                        level: newLevel,
                    })
                    .eq('clerk_user_id', user.id);
            }
        } catch (err) {
            console.error("❌ QuestContext: Failed to grant bonus XP:", err);
        }
    };

    const getProgress = (quest: Quest): number => {
        if (quest.tasks.length === 0) return 0;
        const completed = quest.tasks.filter(t => t.completed).length;
        return Math.round((completed / quest.tasks.length) * 100);
    };

    const totalXP = quests.reduce(
        (sum, q) => sum + q.tasks.filter(t => t.completed).reduce((s, t) => s + (t.earnedXp ?? t.xp), 0),
        0
    );

    return (
        <QuestContext.Provider value={{ quests, addQuest, toggleTask, markTaskComplete, getProgress, totalXP, isLoading, replaceAllQuests, removeQuest, reloadQuests, recordFocusSession, grantBonusXP }}>
            {children}
        </QuestContext.Provider>
    );
}

export function useQuests() {
    const context = useContext(QuestContext);
    if (!context) throw new Error('useQuests must be used within a QuestProvider');
    return context;
}