-- AI Mentor Integration Migration Script
-- Run these in your Supabase SQL Editor

-- 1. Update player_stats with Mentor tracking columns
ALTER TABLE player_stats
  ADD COLUMN IF NOT EXISTS last_mentor_review TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS has_completed_onboarding BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS semester INTEGER DEFAULT 4;

-- 2. Update quests with AI priority columns
ALTER TABLE quests
  ADD COLUMN IF NOT EXISTS ai_priority INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_status TEXT DEFAULT 'active';

-- 3. Create mentor_sessions table to cache AI briefings
CREATE TABLE IF NOT EXISTS mentor_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clerk_user_id TEXT NOT NULL REFERENCES player_stats(clerk_user_id),
  session_type TEXT NOT NULL DEFAULT 'daily_briefing',
  -- types: 'daily_briefing', 'task_review', 'recalibration', 'plan_generation'
  ai_response JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Enable RLS and add policies for all tables (Security Hardening)
-- This ensures each user can ONLY see their own data.

-- Mentor Sessions
ALTER TABLE mentor_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own sessions" ON mentor_sessions;
CREATE POLICY "Users can manage own sessions"
  ON mentor_sessions FOR ALL
  USING (clerk_user_id = auth.jwt() ->> 'sub')
  WITH CHECK (clerk_user_id = auth.jwt() ->> 'sub');

-- Player Stats
ALTER TABLE player_stats ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own stats" ON player_stats;
CREATE POLICY "Users can manage own stats"
  ON player_stats FOR ALL
  USING (clerk_user_id = auth.jwt() ->> 'sub')
  WITH CHECK (clerk_user_id = auth.jwt() ->> 'sub');

-- Subjects
ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own subjects" ON subjects;
CREATE POLICY "Users can manage own subjects"
  ON subjects FOR ALL
  USING (clerk_user_id = auth.jwt() ->> 'sub')
  WITH CHECK (clerk_user_id = auth.jwt() ->> 'sub');

-- Missions
ALTER TABLE missions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own missions" ON missions;
CREATE POLICY "Users can manage own missions"
  ON missions FOR ALL
  USING (clerk_user_id = auth.jwt() ->> 'sub')
  WITH CHECK (clerk_user_id = auth.jwt() ->> 'sub');

-- PYQ Vault
ALTER TABLE pyq_vault ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own pyq" ON pyq_vault;
CREATE POLICY "Users can manage own pyq"
  ON pyq_vault FOR ALL
  USING (clerk_user_id = auth.jwt() ->> 'sub')
  WITH CHECK (clerk_user_id = auth.jwt() ->> 'sub');
