-- =============================================
-- COMBINED FIX MIGRATION
-- Covers: AI Mentor tables + Semester column
-- Run this in Supabase SQL Editor
-- =============================================

-- 1. Add semester column to player_stats (Issue #5)
ALTER TABLE player_stats
  ADD COLUMN IF NOT EXISTS semester INTEGER DEFAULT 4;

-- 2. Add AI mentor tracking columns (Issue #1)
ALTER TABLE player_stats
  ADD COLUMN IF NOT EXISTS last_mentor_review TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 3. Add AI priority columns to quests
ALTER TABLE quests
  ADD COLUMN IF NOT EXISTS ai_priority INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_status TEXT DEFAULT 'active';

-- 4. Create mentor_sessions table (Issue #1 — critical for MentorContext)
CREATE TABLE IF NOT EXISTS mentor_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clerk_user_id TEXT NOT NULL,
  session_type TEXT NOT NULL DEFAULT 'daily_briefing',
  ai_response JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Enable RLS on mentor_sessions
ALTER TABLE mentor_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own sessions" ON mentor_sessions;
CREATE POLICY "Users can manage own sessions"
  ON mentor_sessions FOR ALL
  USING (clerk_user_id = auth.jwt() ->> 'sub')
  WITH CHECK (clerk_user_id = auth.jwt() ->> 'sub');
