-- 1. The Player Profile (Linked to Clerk)
create table player_stats (
  clerk_user_id text primary key, -- This is the ID Clerk gives us
  name text,
  level integer default 1,
  total_xp integer default 0,
  streak_days integer default 0
);

-- 2. The Subjects (Main Questlines)
create table subjects (
  id bigint generated by default as identity primary key,
  clerk_user_id text references player_stats(clerk_user_id),
  title text not null,
  color_hex text,
  progress_percentage integer default 0
);

-- 3. The Topics (Daily Missions)
create table missions (
  id bigint generated by default as identity primary key,
  subject_id bigint references subjects(id) on delete cascade,
  clerk_user_id text references player_stats(clerk_user_id),
  title text not null,
  status text default 'Not Started',
  xp_reward integer default 100
);

-- 4. The PYQ Vault (Archives)
create table pyq_vault (
  id bigint generated by default as identity primary key,
  mission_id bigint references missions(id) on delete cascade,
  clerk_user_id text references player_stats(clerk_user_id),
  year integer,
  status text default 'Needs Revision'
);